export { default as Home } from './Home';
export { default as StoreDetails } from './StoreDetails';
export { default as SellDetails } from './SellDetails';
export { default as SettingsDetails } from './SettingsDetails';
export { default as CartDetails } from './CartDetails';
export { default as Collections } from './Collections';
export { default as PerfumeDetails } from './PerfumeDetails';
export { default as Search } from './Search'
export { default as Error } from './Error';
export { default as Policies } from './Policies'
export { default as AboutDetails } from './AboutDetails'
export { default as Contact } from './Contact'
