export { default as Home } from './Home';
export { default as Profile } from './Profile';
export { default as Settings } from './Settings';
export { default as Sell } from './Sell';
export { default as Cart } from './Cart';
export { default as Collections } from './Collections';
export { default as PerfumeDetails } from './PerfumeDetails';
export { default as Search } from './Search'
export { default as Error } from './Error';